service: nazgul-on-rails

image: tonyyunker/nazgul-on-rails

servers:
  web:
    hosts:
      - 157.245.90.133

registry:
  username: tonyyunker

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RUBY_YJIT_ENABLE: 1
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "data:/data"

proxy:
  ssl: true
  host: nazgul.cc
  app_port: 3000

builder:
  arch: amd64
