-- DDL generated by Postico 1.5.22
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE activities (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    strava_id bigint UNIQUE,
    external_id text,
    name text,
    distance numeric,
    moving_time numeric,
    elapsed_time numeric,
    activity_date date,
    bike text,
    average_speed numeric,
    max_speed numeric,
    average_watts numeric,
    with_kat boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX activities_pkey ON activities(id int4_ops);
CREATE UNIQUE INDEX activities_strava_id_key ON activities(strava_id int8_ops);
